substitutions:
  hostname: "power8x1"
  friendly_name: "PS8x-1"

esphome:
  name: $hostname
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret station_ssid
  password: !secret station_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$hostname"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

switch:
  - platform: gpio
    name: "${friendly_name} socket 1"
    icon: mdi:power-socket-eu
    id: relay_1
    pin: GPIO16
    inverted: true
    restore_mode: restore_default_off
  - platform: gpio
    name: "${friendly_name} socket 2"
    icon: mdi:power-socket-eu
    id: relay_2
    pin: GPIO03
    inverted: true
    restore_mode: restore_default_off
  - platform: gpio
    name: "${friendly_name} socket 3"
    icon: mdi:power-socket-eu
    id: relay_3
    pin: GPIO04
    inverted: false
    restore_mode: restore_default_off
  - platform: gpio
    name: "${friendly_name} socket 4"
    icon: mdi:power-socket-eu
    id: relay_4
    pin: GPIO05
    inverted: false
    restore_mode: restore_default_off
  - platform: gpio
    name: "${friendly_name} socket 5"
    icon: mdi:power-socket-eu
    id: relay_5
    pin: GPIO12
    inverted: false
    restore_mode: restore_default_off
  - platform: gpio
    name: "${friendly_name} socket 6"
    icon: mdi:power-socket-eu
    id: relay_6
    pin: GPIO013
    inverted: false
    restore_mode: restore_default_off
  - platform: gpio
    name: "${friendly_name} socket 7"
    icon: mdi:power-socket-eu
    id: relay_7
    pin: GPIO14
    inverted: false
    restore_mode: restore_default_off
  - platform: gpio
    name: "${friendly_name} socket 8"
    icon: mdi:power-socket-eu
    id: relay_8
    pin: GPIO15
    inverted: false
    restore_mode: restore_default_off
